### ISSUE TITLE
请问您的博客有RSS支持吗？

### ISSUE THREAD

**Issue by mutoe** [godbasin/godbasin.github.io#16]
想通过RSS订阅您的博客，但似乎没有找到atom.xml文件，请问可以支持rss吗?

**Comment by godbasin** [comment]
可以，等找个时间加上

**Comment by godbasin** [comment]
done

**Comment by mutoe** [comment]
good😄

![图片](https://user-images.githubusercontent.com/9391981/55680269-2255a180-594a-11e9-87ed-690a4dba680f.png)
